# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us <Wanglsir@gmail.com, 983708408@qq.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# #### Drawflow uat configuration. ####
#

drawflow:
  web:
    cloud_convert_api_key: ""
    github_client_secret: ""
    github_dev_client_secret: ""
    google_client_id: ""
    google_client_redirect_uri: ""
    google_client_secret: ""
    iconfinder_client_id: ""
    iconfinder_client_secret: ""
    msgraph_client_id: ""
    msgraph_client_redirect_uri: ""
    msgraph_client_secret: ""
    msgraph_dev_client_id: ""
    msgraph_dev_client_secret: ""
  pusher:
    app_id: ""
    key: ""
    secret: ""
    cluster: ""